import streamlit as st
from streamlit_scroll_to_top import scroll_to_here
from components.go_to_page import go_to_page
from _pages.reminder_modal import reminder_modal
from components.ui import inline_notice, page_header, step_card

def instructions_page(isModal=False):
    """Explain the end-to-end workflow with a guided step list."""
    if isModal:
        scroll_to_here(0, key="top")

    if not isModal:
        if st.button("⬅ Back to Home"):
            go_to_page("home")

    page_header(
        "How the workflow works",
        "Follow these steps to request your data, upload it, review flagged content, and decide whether to export or donate the cleaned result.",
        eyebrow="Instructions",
    )

    steps = [
        {
            "title": "Request your ChatGPT export",
            "desc": "In OpenAI, go to Settings, then Data controls, then Export data to request your conversation archive.",
            "gif": "images/ChatGPTExport.gif",
        },
        {
            "title": "Upload your JSON file",
            "desc": "Upload either the unzipped conversations JSON from ChatGPT or the JSON generated by your browser extension.",
            "gif": "images/Upload.gif",
        },
        {
            "title": "Review and clean conversations",
            "desc": "Search through chats, remove conversations you do not want included, and redact sensitive text directly in the review interface.",
            "gif": "images/Review.gif",
        },
        {
            "title": "Export or donate the cleaned result",
            "desc": "Download the cleaned JSON for your records or donate it securely to support the research study.",
            "gif": "images/Donate.gif",
        },
    ]

    for index, step in enumerate(steps, start=1):
        step_card(index, step["title"], step["desc"], image_path=step["gif"])
        # if index == 1 and not isModal:
        #     inline_notice(
        #         "OpenAI often takes 3 to 4 days to deliver the export. You can leave yourself a reminder so you do not lose your place in the workflow.",
        #         tone="info",
        #     )
        #     if st.button("Get Reminder"):
        #         reminder_modal()

    if not isModal:
        if st.button("Go to Upload Page", width="stretch"):
            go_to_page("upload")
